title: shujaat mirza
logo: /assets/img/headshot.png
description: PhD Student, Computer Science NYU Email - first . last [at] nyu [dot] edu
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
