title: shujaat mirza
logo: /assets/img/headshot.jpg
description: PhD Student, Computer Science NYU Email - first . last [at] nyu [dot] edu
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
